O_OBJS := head.o setup.o early_serial.o early_panic.o \
		  idt.o i8253.o i8259.o irq.o traps.o timer.o \
		  proc.o switch_to.o kthread_trampoline.o

O_TARGET := kernelar.o

include $(TOPDIR)/Rules.mk
