CROSS_PREFIX = "x86_64-elf-" # if $CROSS_COMPILE == true, prefix tools with this string

LINKER_SCRIPT = "x86_64-link.ld"
INCLUDE_DIRS = ["include"]

# architecture specific flags
CFLAGS = [
    "-m64",
    "-m80387",
    "-msse",
    "-msse2",
    "-mmmx",
    "-mno-sse3",
    "-mno-sse4",
    "-mno-avx",
    "-mno-avx2",
    "-mno-avx512f",
    "-mcmodel=kernel",
    "-mno-red-zone",
    "-fno-omit-frame-pointer",
]
CPPFLAGS = []
CXXFLAGS = []
ACFLAGS = []
LDFLAGS = []
