#!/usr/bin/env python3

import json


def collect_vectors(value):
    vectors = []
    if isinstance(value, list):
        vectors.extend(value)
    elif isinstance(value, dict):
        if "vectors" in value:
            vectors.extend(value["vectors"])
        if "ranges" in value:
            for r in value["ranges"]:
                vectors.extend(range(r[0], r[1] + 1))
    return vectors


pairs = []

with open("isr_vectors.json") as f:
    config = json.load(f)

    for macro, value in config.items():
        for vector in collect_vectors(value):
            pairs.append((vector, macro))

pairs.sort(key=lambda p: p[0])

print("// autogenerated - do not edit")
print("#include <asi/isr_entry.h>")
print("#include <asi/descriptors.h>")
print(".extern ISR_COMMON_NAME")
print('.section .text, "ax"')
print()

for vector, macro in pairs:
    print(f"{macro}({vector})")

print()
print(".global ISR_TABLE_NAME")
print("ISR_TABLE_NAME:")

for vector, macro in pairs:
    print(f"    .byte {vector}")
    print("    .short 0x8")  # temporairly fixed
    print("    .byte 0")
    print("    .byte GATE_INTERRUPT")
    print("    .byte 0")
    print("    .short 0")
    print(f"    .quad ISR_ENTRY_NAME({vector})")

# null terminate the table
print("    .byte 0")
print("    .short 0")
print("    .byte 0")
print("    .byte 0")
print("    .byte 0")
print("    .short 0")
print("    .quad 0")
